### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by IdkWhatIShouldUseforausername** [yoshiquest/forge-clj#36]
Hello I'm new to clojure and I have done forge mods before and I wanted to test this. But when I tried running my mod I got an error.
'warnOnReflection' is deprecated and will go away in a future version. Please use 'clojure.warnOnReflection' instead.
'aotCompile' is deprecated and will go away in a future version. Please use 'clojure.aotCompile' instead.
#################################################
         ForgeGradle 2.1-SNAPSHOT-17806f4        
  https://github.com/MinecraftForge/ForgeGradle  
#################################################
               Powered by MCP unknown               
             http://modcoderpack.com             
         by: Searge, ProfMobius, Fesh0r,         
         R4wk, ZeuX, IngisKahn, bspkrs           
#################################################
Version string '' does not match SemVer specification 
You should try SemVer : http://semver.org/
:deobfCompileDummyTask
:deobfProvidedDummyTask
:compileApiClojure UP-TO-DATE
:sourceApiJava UP-TO-DATE
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:compileClojure
Exception in thread "main" java.lang.IllegalArgumentException: No value supplied for key: 1.0, compiling:(null:77:1)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.load(Compiler.java:7326)
	at clojure.core$load_reader.invokeStatic(core.clj:3957)
	at clojure.main$script_opt.invokeStatic(main.clj:335)
	at clojure.main$script_opt.invoke(main.clj:330)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: No value supplied for key: 1.0
	at clojure.lang.PersistentHashMap.create(PersistentHashMap.java:77)
	at clojure.core$hash_map.invokeStatic(core.clj:387)
	at clojure.core$hash_map.doInvoke(core.clj:379)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at forge_clj.core$defmod.invokeStatic(core.clj:26)
	at forge_clj.core$defmod.doInvoke(core.clj:17)
	at clojure.lang.RestFn.invoke(RestFn.java:497)
	at clojure.lang.Var.invoke(Var.java:401)
	at clojure.lang.AFn.applyToHelper(AFn.java:171)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:6776)
	at clojure.lang.Compiler.macroexpand(Compiler.java:6837)
	at clojure.lang.Compiler.compile1(Compiler.java:7459)
	at clojure.lang.Compiler.compile(Compiler.java:7541)
	at clojure.lang.RT.compile(RT.java:406)
	at clojure.lang.RT.load(RT.java:451)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$compile$fn__5682.invoke(core.clj:5903)
	at clojure.core$compile.invokeStatic(core.clj:5903)
      ojure.core$compile.invoke(core.clj:5895)
	at clojuresque.tasks.compile$eval43$main_task_driver__45$fn__49.invoke(Unknown Source)
	at clojuresque.tasks.compile$eval43$main_task_driver__45.invoke(Unknown Source)
	at clojuresque.tasks.compile$eval43$main__58.invoke(Unknown Source)
	at clojuresque.tasks.compile$eval63.invokeStatic(Unknown Source)
	at clojuresque.tasks.compile$eval63.invoke(Unknown Source)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 11 more
:compileClojure FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileClojure'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1

I'm on Linux

**Comment by IdkWhatIShouldUseforausername** [comment]
fixed

**Comment by ryanhaney97** [comment]
Closing this then since you fixed it.
